# Generated by Django 3.1.4 on 2020-12-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='номер поезда')),
                ('travel_time', models.PositiveSmallIntegerField(verbose_name='время в пути')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city_set', to='travels.city', verbose_name='из какого города')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city_set', to='travels.city', verbose_name='в какой город')),
            ],
            options={
                'verbose_name': 'поезд',
                'verbose_name_plural': 'поезда',
                'ordering': ['travel_time'],
            },
        ),
    ]
